language: generic
sudo: required
services:
  - docker

# commands to run before deploy / test
before_install:
  # build docker image out of client (build context ./client)
  - docker build -f ./client/Dockerfile.dev -t tamplier2911/docker-mca-client-test ./client

# command to run tests suite
script:
  # create and run a container out of image
  # set invironment variable of CI to true
  # re-write startup command to run tests suite
  - docker run -e CI=true tamplier2911/docker-mca-client-test npm run test

# after script successfuly ran
after_success:
  # run builds for each project
  - docker build -f ./client/Dockerfile -t tamplier2911/docker-mca-client-prod ./client
  - docker build -f ./nginx/Dockerfile -t tamplier2911/docker-mca-nginx-prod ./nginx
  - docker build -f ./server/Dockerfile -t tamplier2911/docker-mca-server-prod ./server
  - docker build -f ./worker/Dockerfile -t tamplier2911/docker-mca-worker-prod ./worker

  # make sure travis has docker id and pass as environment variables
  # log to docker hub cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # once prod images ready - push them to docker hub
  - docker push tamplier2911/docker-mca-client-prod
  - docker push tamplier2911/docker-mca-nginx-prod
  - docker push tamplier2911/docker-mca-server-prod
  - docker push tamplier2911/docker-mca-worker-prod
