# Select base image
FROM node:alpine

# Create app directory
RUN mkdir /app

# Select work dir
WORKDIR /app

# Copy required files
# COPY . /app
COPY package.json .

# Run command to install dependencies
RUN npm install

# Copy rest of the files
COPY ./ ./

# Startup Command
CMD [ "npm", "run", "start" ]
