version: "3"
services:
  docker-cra:
    image: tamplier2911/docker-compose-cra
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - /app/node_modules
      - .:/app
    stdin_open: true
  docker-cra-test:
    image: tamplier2911/docker-compose-cra-test
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - /app/node_modules
      - .:/app
    stdin_open: true
    command: ["npm", "run", "test"]
