version: "3"
services:
  docker-cra:
    image: tamplier2911/docker-compose-cra
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
    stdin_open: true
