# Select base image
FROM node:alpine

# Create app directory
RUN mkdir /app

# Select work dir
WORKDIR /app

# Select required files
COPY . /app

# Run command
RUN npm install

# Copy rest of the files
# COPY ./ ./

# Startup Command
CMD [ "npm", "run", "start" ]